import { v4 as uuidv4 } from 'uuid';
export const all_jobs = [
    {
        id: uuidv4(),
        title: 'Research on Cardiovascular Disease Prevention',
        proposedBudget: "2500",
        datePosted: "Fri Jun 14 2024 10:20:19 GMT+0300 (East Africa Time)",
        description: 'Study the effectiveness of various lifestyle changes and medications in preventing heart diseases...',
        skills: ['Cardiology', 'Epidemiology', 'Data Analysis', 'Public Health'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Genetic Basis of Rare Diseases',
        proposedBudget: "3000",
        datePosted: "Sun Aug 15 2015 21:05:40 GMT+0300 (East Africa Time)",
        description: 'Investigate the genetic mutations responsible for rare hereditary diseases...',
        skills: ['Genetics', 'Molecular Biology', 'Sequencing', 'Data Analysis'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Impact of Nutrition on Mental Health',
        proposedBudget: "4000",
        datePosted: "Thu Apr 25 2024 10:20:19 GMT+0300 (East Africa Time)",
        description: 'Explore the relationship between dietary patterns and mental health outcomes...',
        skills: ['Nutrition', 'Psychiatry', 'Epidemiology', 'Statistical Analysis'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Evaluation of New Cancer Therapies',
        proposedBudget: "4500",
        datePosted: "Thu Oct 12 2016 18:05:40 GMT+0300 (East Africa Time)",
        description: 'Assess the efficacy and safety of novel treatments for various cancers...',
        skills: ['Oncology', 'Clinical Trials', 'Molecular Biology', 'Data Management'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Diabetes Management in Different Populations',
        proposedBudget: "2000",
        datePosted: "Mon Apr 03 2017 09:55:15 GMT+0300 (East Africa Time)",
        description: 'Analyze how different demographics respond to diabetes management strategies...',
        skills: ['Endocrinology', 'Public Health', 'Data Analysis', 'Clinical Research'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Long-term Effects of COVID-19',
        proposedBudget: "3500",
        datePosted: "Thu Jul 30 2020 22:45:50 GMT+0300 (East Africa Time)",
        description: 'Investigate the long-term health impacts of COVID-19 on patients...',
        skills: ['Virology', 'Epidemiology', 'Clinical Research', 'Data Collection'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Chronic Pain Management Techniques',
        proposedBudget: "3200",
        datePosted: "Fri Feb 14 2022 02:35:20 GMT+0300 (East Africa Time)",
        description: 'Study various techniques and their effectiveness in managing chronic pain...',
        skills: ['Pain Management', 'Clinical Trials', 'Data Analysis', 'Patient Care'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Health Economics of Vaccination Programs',
        proposedBudget: "3800",
        datePosted: "Sun Aug 10 2023 16:25:30 GMT+0300 (East Africa Time)",
        description: 'Analyze the economic benefits of vaccination programs in different regions...',
        skills: ['Health Economics', 'Public Health', 'Policy Analysis', 'Statistical Modeling'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Innovations in Surgical Procedures',
        proposedBudget: "2800",
        datePosted: "Tue Mar 28 2018 04:50:55 GMT+0300 (East Africa Time)",
        description: 'Research new surgical techniques and their outcomes compared to traditional methods...',
        skills: ['Surgery', 'Clinical Research', 'Data Analysis', 'Medical Technology'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Mental Health Interventions for Adolescents',
        proposedBudget: "3300",
        datePosted: "Mon Apr 20 2015 11:30:25 GMT+0300 (East Africa Time)",
        description: 'Develop and evaluate interventions aimed at improving mental health in adolescents...',
        skills: ['Psychology', 'Public Health', 'Clinical Trials', 'Data Analysis'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'AI in Diagnostic Radiology',
        proposedBudget: "3700",
        datePosted: "Tue Jan 01 2024 10:20:19 GMT+0300 (East Africa Time)",
        description: 'Study the application of artificial intelligence in improving diagnostic accuracy in radiology...',
        skills: ['Radiology', 'Artificial Intelligence', 'Machine Learning', 'Data Analysis'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Public Health Impact of Smoking Cessation Programs',
        proposedBudget: "3400",
        datePosted: "Mon Dec 05 2019 13:15:10 GMT+0300 (East Africa Time)",
        description: 'Evaluate the effectiveness of various smoking cessation programs on public health...',
        skills: ['Public Health', 'Epidemiology', 'Program Evaluation', 'Data Analysis'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Development of New Antiviral Drugs',
        proposedBudget: "4100",
        datePosted: "Tue Mar 28 2018 04:50:55 GMT+0300 (East Africa Time)",
        description: 'Research and develop new drugs to combat viral infections...',
        skills: ['Pharmacology', 'Virology', 'Drug Development', 'Molecular Biology'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Nutritional Interventions for Obesity',
        proposedBudget: "3600",
        datePosted: "Mon Jul 25 2016 07:55:15 GMT+0300 (East Africa Time)",
        description: 'Investigate the impact of various nutritional interventions on obesity...',
        skills: ['Nutrition', 'Clinical Research', 'Public Health', 'Data Analysis'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Social Determinants of Health in Urban Areas',
        proposedBudget: "2700",
        datePosted: "Fri May 08 2020 18:35:20 GMT+0300 (East Africa Time)",
        description: 'Study how social factors influence health outcomes in urban populations...',
        skills: ['Public Health', 'Sociology', 'Epidemiology', 'Data Analysis'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Neurodegenerative Disease Research',
        proposedBudget: "5000",
        datePosted: "Tue Feb 14 2017 21:05:40 GMT+0300 (East Africa Time)",
        description: 'Investigate the mechanisms and potential treatments for neurodegenerative diseases...',
        skills: ['Neuroscience', 'Molecular Biology', 'Clinical Research', 'Data Analysis']
    },
    {
        id: uuidv4(),
        title: 'Policy Analysis for Healthcare Access',
        proposedBudget: "3900",
        datePosted: "Thu Nov 30 2022 09:45:50 GMT+0300 (East Africa Time)",
        description: 'Analyze policies aimed at improving healthcare access for underserved populations...',
        skills: ['Health Policy', 'Public Health', 'Policy Analysis', 'Data Collection']
    },
    {
        id: uuidv4(),
        title: 'Toxicological Effects of Environmental Pollutants',
        proposedBudget: "3500",
        datePosted: "Wed Sep 13 2019 14:25:10 GMT+0300 (East Africa Time)",

        description: 'Study the health impacts of exposure to environmental pollutants...',
        skills: ['Toxicology', 'Environmental Health', 'Data Analysis', 'Risk Assessment'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Immunotherapy for Autoimmune Diseases',
        proposedBudget: "4200",
        datePosted: "Mon Mar 05 2023 08:15:30 GMT+0300 (East Africa Time)",

        description: 'Research new immunotherapy treatments for autoimmune diseases...',
        skills: ['Immunology', 'Clinical Research', 'Molecular Biology', 'Data Analysis'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    },
    {
        id: uuidv4(),
        title: 'Cardiovascular Health in Elderly Populations',
        proposedBudget: "4600",
        datePosted: "Fri Jun 14 2024 10:20:19 GMT+0300 (East Africa Time)",
        description: 'Investigate factors affecting cardiovascular health in the elderly and develop interventions...',
        skills: ['Cardiology', 'Geriatrics', 'Clinical Research', 'Data Analysis'],
        job_guid: '1',
        user_guid: 'user1',
        comments: 'First job',
        status: 'Open',
        submission_date: '2023-06-01',
    }
];


export const top100SkillsInMedicalResearch = [
    "Clinical Research",
    "Data Analysis",
    "Biostatistics",
    "Molecular Biology",
    "Cell Culture",
    "Laboratory Skills",
    "Statistical Analysis",
    "Scientific Writing",
    "Genomics",
    "Proteomics",
    "Bioinformatics",
    "Clinical Trials",
    "Good Clinical Practice (GCP)",
    "Regulatory Affairs",
    "Epidemiology",
    "Grant Writing",
    "Project Management",
    "Pharmacology",
    "Tissue Culture",
    "Western Blotting",
    "ELISA",
    "PCR",
    "Flow Cytometry",
    "Microscopy",
    "Immunohistochemistry",
    "In Vivo Studies",
    "In Vitro Studies",
    "CRISPR",
    "Gene Editing",
    "Next-Generation Sequencing (NGS)",
    "RNA Sequencing",
    "Protein Purification",
    "Mass Spectrometry",
    "Translational Research",
    "Pathology",
    "Histology",
    "Pharmaceutical Development",
    "Drug Discovery",
    "Toxicology",
    "Neuroscience",
    "Oncology",
    "Immunology",
    "Virology",
    "Microbiology",
    "Clinical Data Management",
    "Medical Writing",
    "Regulatory Compliance",
    "Ethics in Research",
    "Patient Recruitment",
    "Randomized Controlled Trials",
    "Human Subjects Research",
    "Survey Design",
    "Meta-Analysis",
    "Systematic Review",
    "Health Services Research",
    "Chronic Disease Research",
    "Behavioral Science",
    "Public Health",
    "Health Economics",
    "Patient Safety",
    "Clinical Outcome Assessment",
    "Medical Device Research",
    "Pharmacovigilance",
    "Quality Assurance",
    "SAS Programming",
    "R Programming",
    "SPSS",
    "STATA",
    "SQL",
    "Machine Learning",
    "Artificial Intelligence in Medicine",
    "Health Informatics",
    "Biotechnology",
    "CRF Design",
    "Database Management",
    "Laboratory Management",
    "Protocol Development",
    "Patient-Centered Research",
    "Comparative Effectiveness Research",
    "Health Policy Research",
    "Healthcare Innovation",
    "Personalized Medicine",
    "Clinical Research Coordination",
    "Clinical Monitoring",
    "Biomarker Discovery",
    "Biological Assays",
    "Therapeutic Areas Knowledge",
    "Transgenic Models",
    "Biophysics",
    "Chemistry",
    "Nanotechnology in Medicine",
    "Biomedical Engineering",
    "Radiology",
    "Medical Imaging",
    "Biomaterials",
    "Pharmacokinetics",
    "Pharmacodynamics",
    "Stem Cell Research",
    "Regenerative Medicine",
    "Vaccinology",
    "Zoonotic Diseases",
    "Healthcare Delivery Research"
];


